### ISSUE TITLE
feat: auth for mobile

### ISSUE THREAD

**Issue by EkaanshArora** [juliusmarminge/acme-corp#13]
### Describe the feature you'd like to request

Would love to see adding Auth for Expo. The new Clerk docs list support for using OAuth on Expo like [this](https://beta-docs.clerk.com/quickstarts/expo#build-your-sign-up). This will enable the mobile app to be more useful if it can share Auth from Next.

Sidenote: The repo looks awesome, I've tried setting up something similar before using T3-Turbo but haven't been able to get Clerk working. Tried their template as well, getting the native linking to work reliably was a struggle. Would love to see how you approach this.

### Describe the solution you'd like to see

We can use OAuth with the Clerk Expo package as described [here](https://beta-docs.clerk.com/quickstarts/expo#build-your-sign-up).

### Additional information

Let me know if this is interesting and useful, I am happy to give this a shot if you're busy with other things.

**Comment by juliusmarminge** [comment]
Will add - i just pushed this to github cause i needed help debigging something but its far from ready...

**Comment by EkaanshArora** [comment]
Looking forward to it, happy to help!
