### ISSUE TITLE
bug: tRPC completely brakes when deployed on Vercel

### ISSUE THREAD

**Issue by aetairidis** [juliusmarminge/acme-corp#136]
### Provide environment information

 System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 53.19 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.9.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v19.9.0/bin/npm

### Describe the bug

tRPC only works locally, when deployed on Vercel cloud i get the following error

 TRPCClientError: Unable to transform response from server
    at (../../node_modules/@trpc/client/dist/transformResult-9a244fe7.mjs:75:14)
    at (../../node_modules/@trpc/client/dist/httpBatchLink-e66c0674.mjs:185:44) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  name: 'TRPCClientError'
}

### Link to reproduction

tRPC

### To reproduce

Deploy as usual, and then deploy on Vercel Cloud.

### Additional information

Have already ensured all of the environmental variables are correctly set on Vercel.

**Comment by juliusmarminge** [comment]
https://acme-corp.jumr.dev is deployed on Vercel and works

**Comment by christophmeise** [comment]
I have the exact same issue. The deployment is successful and I can login with Clerk. All pages that are deployed on the edge and use tRPC break with the mentioned error. As a quickfix I moved all routes using tRPC to lambda instead of edge.
