### ISSUE TITLE
bug: This repo isn't pinned in your Github profile

### ISSUE THREAD

**Issue by t3dotgg** [juliusmarminge/acme-corp#159]
### Provide environment information

Chrome

### Describe the bug

I went to your profile, and you only have t3-oss repos pinned

### Link to reproduction

https://github.com/juliusmarminge

### To reproduce

Go to https://github.com/juliusmarminge, realize acme-corp isn't in the pins, go to repos, and scroll until you find it

**Comment by juliusmarminge** [comment]
Crisis averted 👍🏼 

<img width="1034" alt="CleanShot 2023-08-09 at 00 36 10@2x" src="https://github.com/juliusmarminge/acme-corp/assets/51714798/f147c7ba-6034-4646-9ffe-b9db20e8ca5f">
