### ISSUE TITLE
bug: The Profile modal is not showing the whole component

### ISSUE THREAD

**Issue by matallui** [juliusmarminge/acme-corp#21]
### Provide environment information

N/A

### Describe the bug

After logging in, if I click on Profile in the user menu, the modal hides most of the content.

### Link to reproduction

https://acme-corp.jumr.dev/

### To reproduce

Go to demo application link above, sign-in, then access the user profile via user menu.

### Additional information

I didn't run this locally, so this was just found by experimenting on your demo.

**Comment by juliusmarminge** [comment]
This is known - got clerk people on it ☺️

**Comment by perkinsjr** [comment]
This is fixed by #33 or at least the start of correct sizing
