### ISSUE TITLE
bug: @@map is not supported by Prisma-generator-kysely

### ISSUE THREAD

**Issue by bachiitter** [juliusmarminge/acme-corp#24]
### Provide environment information

N/A

### Describe the bug

The issue with the Prisma model and Prisma-generator-kysely arises when using the @@map directive. When using @@map, the Prisma-generator-kysely does not output types properly. Instead of using the value for the object key from @@map, it uses the model name. This can result in inconsistencies and errors when trying to use the generated types.

### Link to reproduction

https://acme-corp.jumr.dev/

### To reproduce

To reproduce the issue with the Prisma model and Prisma-generator-kysely not outputting types properly when using @@map, follow these steps:

Create a new Prisma model with a field that uses the @@map directive, for example:
``` prisma
model User {
  id       Int      @id @default(autoincrement())
  username String   @unique
 @@map("users")
}

```
Run the Prisma-generator-kysely to generate the database schema and code for the model.

Check the generated code for the User model, specifically the TypeScript types for the fields. You may notice that the generated code uses the model field name instead of the @@map directive value, resulting in inconsistent and incorrect types.

Attempt to use the generated code in your project, and you may encounter errors or inconsistencies due to the incorrect types.

**Comment by juliusmarminge** [comment]
Sorry if this comes out a bit rude, but if it's a bug in the generator why aren't you opening an issue there?

**Comment by bachitterch** [comment]
> Owner

My bad! I realize I should have open issue there first and been clearer in my previous message. What I was hoping for is if you could add a note in the README file advising users to avoid using "@@map" in the model to prevent errors.

**Comment by bachitterch** [comment]
Possible fix if you can replace Prisma-generator-kysely with prisma-kysely as it does support @@map

**Comment by valtyr** [comment]
@FlatMapIO I just released a new version that adds support for field level map (@map). Model level map (@@map) has been supported for a while now though.

**Comment by FlatMapIO** [comment]
@FlatMapIO Thank you for your contribution :100: , I have used it as soon as I could

**Comment by valtyr** [comment]
@FlatMapIO My pleasure, I'm happy you find it useful :D

@juliusmarminge I've attempted to address some of the shortcomings of `prisma-generator-kysely` with [`prisma-kysely`](http://github.com/valtyr/prisma-kysely). It goes with out saying that you're welcome to use it in your template if you want. It should be a 1 to 1 swap.

**Comment by juliusmarminge** [comment]
> @juliusmarminge I've attempted to address some of the shortcomings of prisma-generator-kysely with [prisma-kysely](https://github.com/valtyr/prisma-kysely). It goes with out saying that you're welcome to use it in your template if you want. It should be a 1 to 1 swap.

I'll take a look when i pick this back up. Had to take a break cause other stuff got in the way, but I'm definetely not done with this project yet!
