### ISSUE TITLE
feat: demo how to use tRPC in Next app

### ISSUE THREAD

**Issue by matallui** [juliusmarminge/acme-corp#37]
### Describe the feature you'd like to request

Currently there's no example in this codebase how to perform tRPC API requests from the Next application (using the app directory). It'd be good to have an example.

### Describe the solution you'd like to see

Would like to see how to use tRPC with Next app directory. I've tried following a couple of examples but without success, so not sure if this is possible or not as of now.

**Comment by juliusmarminge** [comment]
Yep - it's coming.

I had to take a break from this but will get to the dashboard app soon!
