### ISSUE TITLE
bug: Incorrect auth flow

### ISSUE THREAD

**Issue by FlatMapIO** [juliusmarminge/acme-corp#38]
### Provide environment information

None

### Describe the bug

The current flow sends two login emails at the same time, and unregistered users cannot create users in Clerk.

After some experimentation, the clerk's authentication workflow seems to look like this.

SignIn flow:
```tsx
await signIn.create({
  strategy: 'email_link',
  identifier: state.email,
  redirectUrl: `${window.location.origin}/`,
})

// user has account in clerk, email sent
// else throw: status===422 => this email is not signed up in clerk
```

SignUp flow:
```tsx
await signUp.create({
    emailAddress: state.email,
    password: nanoid(), // If the password is not provided, there seems to be some problems with the follow-up process? 
  })

await signUp.startMagicLinkFlow({
    redirectUrl: `${window.location.origin}/`,
  })

// email sent, click the link will verify and create the user, redirect to home
// or throw status===422: account exists
```

### Link to reproduction

https://acme-corp.jumr.dev/signin

### To reproduce

The current flow sends two login emails at the same time, and unregistered users cannot create users in Clerk.

<img width="426" alt="截屏2023-04-27 18 23 50" src="https://user-images.githubusercontent.com/1720349/234835305-eecbda09-dcf2-4c49-9067-07d327275d78.png">

**Comment by juliusmarminge** [comment]
cc https://github.com/perkinsjr

**Comment by perkinsjr** [comment]
Look tonight / tomorrow

**Comment by perkinsjr** [comment]
I cannot recreate this on deployed link. Works fine a single email sent, for both sign in and sign up. Both allow logins.

**Comment by juliusmarminge** [comment]
<img width="325" alt="CleanShot 2023-04-28 at 09 31 36@2x" src="https://user-images.githubusercontent.com/51714798/235083743-23874ebd-6d54-40ce-902d-2b0cf7217408.png">


I actually got 2 links now too

**Comment by perkinsjr** [comment]
sorry been busy getting ready for SF look at this tonight

**Comment by FlatMapIO** [comment]
The issue still exists, where if a user has not signed up with their email before, they will receive two emails simultaneously.

**Comment by juliusmarminge** [comment]
Ah yea - I think James is on it. Will have more time for this project in a week or two. Will get all sorted then.
