### ISSUE TITLE
@acme/eslint-config does not exist

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [juliusmarminge/acme-corp#53]
### Provide environment information

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 6.96 GB / 31.93 GB
  Binaries:
    Node: 18.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - D:\Program Files\nodejs\npm.CMD

### Describe the bug

pnpm was not able to find this dependency

### Link to reproduction

-

### To reproduce

pnpm install

**Comment by FleetAdmiralJakob** [comment]
And I can't find some other @acme packages. No clue why

**Comment by juliusmarminge** [comment]
Should prefer workspace https://github.com/juliusmarminge/acme-corp/blob/0d0a2953f51372be8ac0b6f33a305507a5343cb3/.npmrc#L18
